-- Gerado de banco/gestao.db; SHA-256: ed36954661652c7c1f07c8df1d07c724376e03eba4d599372db14cbcaf044ab4
-- Execute somente no projeto Supabase correto e vazio. Arquivo UTF-8.


-- 01: estrutura. Sem políticas de acesso; RLS e revogações bloqueiam anon/authenticated.

-- TEXT e BIGINT preservam valores legados; REAL vira NUMERIC para valores decimais.

BEGIN;

CREATE TABLE public."caixas" (
  "nome" TEXT PRIMARY KEY,
  "valor" NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public."caixas" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."caixas" FROM anon, authenticated;

CREATE TABLE public."condominios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "responsavel" TEXT NOT NULL,
  "responsabilidade" TEXT NOT NULL DEFAULT 'Imobiliária',
  "valor_total" NUMERIC NOT NULL DEFAULT 0,
  "valor_parcela" NUMERIC NOT NULL DEFAULT 0,
  "parcelas" BIGINT NOT NULL DEFAULT 0,
  "parcelas_pagas" BIGINT NOT NULL DEFAULT 0,
  "vencimento" TEXT NOT NULL DEFAULT '',
  "contrato_numero" BIGINT,
  "administradora" TEXT NOT NULL DEFAULT '',
  "pago_ate" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE public."condominios" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."condominios" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."condominios_id_seq" FROM anon, authenticated;

CREATE TABLE public."config" (
  "chave" TEXT PRIMARY KEY,
  "valor" TEXT NOT NULL
);
ALTER TABLE public."config" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."config" FROM anon, authenticated;

CREATE TABLE public."contratos" (
  "numero" BIGINT PRIMARY KEY,
  "proprietario" TEXT NOT NULL DEFAULT '',
  "chave_pix" TEXT NOT NULL DEFAULT '',
  "inquilino" TEXT NOT NULL DEFAULT '',
  "endereco" TEXT NOT NULL DEFAULT '',
  "mes_reajuste" TEXT NOT NULL DEFAULT '',
  "aluguel" NUMERIC NOT NULL DEFAULT 0,
  "garantia" TEXT NOT NULL DEFAULT '',
  "caucao" NUMERIC NOT NULL DEFAULT 0,
  "adiantado" NUMERIC NOT NULL DEFAULT 0,
  "tx_incendio" NUMERIC NOT NULL DEFAULT 0,
  "fianca" NUMERIC NOT NULL DEFAULT 0,
  "condominio" NUMERIC NOT NULL DEFAULT 0,
  "iptu" NUMERIC NOT NULL DEFAULT 0,
  "agua_luz" NUMERIC NOT NULL DEFAULT 0,
  "pct_imob" NUMERIC NOT NULL DEFAULT 0.1,
  "vencimento_dia" BIGINT NOT NULL DEFAULT 10,
  "ativo" BIGINT NOT NULL DEFAULT 1,
  "obs" TEXT NOT NULL DEFAULT '',
  "proprietario_id" BIGINT,
  "inquilino_id" BIGINT,
  "imovel_id" BIGINT
);
ALTER TABLE public."contratos" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."contratos" FROM anon, authenticated;

CREATE TABLE public."despesas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" TEXT NOT NULL,
  "categoria" TEXT NOT NULL DEFAULT 'ordinária',
  "valor" NUMERIC NOT NULL DEFAULT 0,
  "vencimento" TEXT NOT NULL DEFAULT '',
  "situacao" TEXT NOT NULL DEFAULT 'pendente',
  "competencia" TEXT NOT NULL DEFAULT '',
  "origem" TEXT NOT NULL DEFAULT 'Imobiliária'
);
ALTER TABLE public."despesas" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."despesas" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."despesas_id_seq" FROM anon, authenticated;

CREATE TABLE public."imoveis" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "endereco" TEXT NOT NULL,
  "tem_iptu" BIGINT NOT NULL DEFAULT 0,
  "tem_condominio" BIGINT NOT NULL DEFAULT 0,
  "relogio_agua" TEXT NOT NULL DEFAULT '',
  "relogio_luz" TEXT NOT NULL DEFAULT '',
  "obs" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE public."imoveis" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."imoveis" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."imoveis_id_seq" FROM anon, authenticated;

CREATE TABLE public."iptus" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "responsavel" TEXT NOT NULL,
  "responsabilidade" TEXT NOT NULL DEFAULT 'Imobiliária',
  "valor_total" NUMERIC NOT NULL DEFAULT 0,
  "valor_parcela" NUMERIC NOT NULL DEFAULT 0,
  "parcelas" BIGINT NOT NULL DEFAULT 0,
  "parcelas_pagas" BIGINT NOT NULL DEFAULT 0,
  "vencimento" TEXT NOT NULL DEFAULT '',
  "contrato_numero" BIGINT,
  "indice_cadastral" TEXT NOT NULL DEFAULT '',
  "cpf_titular" TEXT NOT NULL DEFAULT '',
  "codigo_acesso" TEXT NOT NULL DEFAULT '',
  "pago_ate" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE public."iptus" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."iptus" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."iptus_id_seq" FROM anon, authenticated;

CREATE TABLE public."lancamentos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contrato_numero" BIGINT NOT NULL,
  "competencia" TEXT NOT NULL,
  "aluguel" NUMERIC NOT NULL DEFAULT 0,
  "caucao" NUMERIC NOT NULL DEFAULT 0,
  "adiantado" NUMERIC NOT NULL DEFAULT 0,
  "tx_incendio" NUMERIC NOT NULL DEFAULT 0,
  "fianca" NUMERIC NOT NULL DEFAULT 0,
  "condominio" NUMERIC NOT NULL DEFAULT 0,
  "iptu" NUMERIC NOT NULL DEFAULT 0,
  "agua_luz" NUMERIC NOT NULL DEFAULT 0,
  "pct_imob" NUMERIC NOT NULL DEFAULT 0.1,
  "vencimento_dia" BIGINT NOT NULL DEFAULT 10,
  "recebido_em" TEXT,
  "via" TEXT NOT NULL DEFAULT '',
  "repassado_em" TEXT,
  "obs" TEXT NOT NULL DEFAULT '',
  UNIQUE ("contrato_numero", "competencia"),
  FOREIGN KEY ("contrato_numero") REFERENCES public."contratos" ("numero")
);
ALTER TABLE public."lancamentos" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."lancamentos" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."lancamentos_id_seq" FROM anon, authenticated;

CREATE TABLE public."leads" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "telefone" TEXT NOT NULL DEFAULT '',
  "email" TEXT NOT NULL DEFAULT '',
  "origem" TEXT NOT NULL DEFAULT '',
  "interesse" TEXT NOT NULL DEFAULT 'alugar',
  "procura" TEXT NOT NULL DEFAULT '',
  "obs" TEXT NOT NULL DEFAULT '',
  "criado_em" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE public."leads" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."leads" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."leads_id_seq" FROM anon, authenticated;

CREATE TABLE public."manutencoes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "solicitante" TEXT NOT NULL DEFAULT '',
  "origem" TEXT NOT NULL DEFAULT 'WhatsApp',
  "contrato_numero" BIGINT,
  "detalhes" TEXT NOT NULL DEFAULT '',
  "situacao" TEXT NOT NULL DEFAULT 'pendente',
  "data_abertura" TEXT NOT NULL DEFAULT '',
  "data_programada" TEXT NOT NULL DEFAULT '',
  "concluida_por" TEXT NOT NULL DEFAULT '',
  "data_conclusao" TEXT NOT NULL DEFAULT '',
  "valor_materiais" NUMERIC NOT NULL DEFAULT 0,
  "valor_mao_obra" NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public."manutencoes" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."manutencoes" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."manutencoes_id_seq" FROM anon, authenticated;

CREATE TABLE public."notas_fiscais" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contrato_numero" BIGINT NOT NULL,
  "competencia" TEXT NOT NULL,
  "valor" NUMERIC NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'a emitir',
  "emitida_em" TEXT,
  "obs" TEXT NOT NULL DEFAULT '',
  "atividade" TEXT NOT NULL DEFAULT 'aluguel',
  UNIQUE ("contrato_numero", "competencia")
);
ALTER TABLE public."notas_fiscais" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."notas_fiscais" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."notas_fiscais_id_seq" FROM anon, authenticated;

CREATE TABLE public."pendencias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" TEXT NOT NULL,
  "ref_id" BIGINT NOT NULL DEFAULT 0,
  "descricao" TEXT NOT NULL DEFAULT '',
  "contrato_numero" BIGINT,
  "competencia" TEXT NOT NULL,
  "valor" NUMERIC NOT NULL DEFAULT 0,
  "criada_em" TEXT NOT NULL DEFAULT '',
  "repassado_em" TEXT,
  UNIQUE ("tipo", "ref_id", "competencia")
);
ALTER TABLE public."pendencias" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."pendencias" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."pendencias_id_seq" FROM anon, authenticated;

CREATE TABLE public."pessoas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" TEXT NOT NULL DEFAULT 'inquilino',
  "nome" TEXT NOT NULL,
  "cpf" TEXT NOT NULL DEFAULT '',
  "email" TEXT NOT NULL DEFAULT '',
  "telefone" TEXT NOT NULL DEFAULT '',
  "aniversario" TEXT NOT NULL DEFAULT '',
  "forma_repasse" TEXT NOT NULL DEFAULT '',
  "dados_bancarios" TEXT NOT NULL DEFAULT '',
  "obs" TEXT NOT NULL DEFAULT '',
  "rg" TEXT NOT NULL DEFAULT '',
  "endereco" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE public."pessoas" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."pessoas" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."pessoas_id_seq" FROM anon, authenticated;

CREATE TABLE public."seguros" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seguradora" TEXT NOT NULL,
  "contrato_numero" BIGINT,
  "valor_parcela" NUMERIC NOT NULL DEFAULT 0,
  "vencimento" TEXT NOT NULL DEFAULT '',
  "parcelas" BIGINT NOT NULL DEFAULT 0,
  "parcelas_pagas" BIGINT NOT NULL DEFAULT 0,
  "obs" TEXT NOT NULL DEFAULT '',
  "pago_ate" TEXT NOT NULL DEFAULT ''
);
ALTER TABLE public."seguros" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."seguros" FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public."seguros_id_seq" FROM anon, authenticated;

COMMIT;
