"""Gera scripts para o SQL Editor do Supabase a partir do SQLite local.

O script com registros fica em supabase/sql-editor/02_dados.sql, ignorado pelo Git.
Execute com: python scripts/export_sqlite_to_supabase.py
"""

from __future__ import annotations

import hashlib
import math
import sqlite3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "banco" / "gestao.db"
OUTPUT = ROOT / "supabase" / "sql-editor"
TABLES = (
    "caixas",
    "condominios",
    "config",
    "contratos",
    "despesas",
    "imoveis",
    "iptus",
    "lancamentos",
    "leads",
    "manutencoes",
    "notas_fiscais",
    "pendencias",
    "pessoas",
    "seguros",
)
TYPE_MAP = {"INTEGER": "BIGINT", "REAL": "NUMERIC", "TEXT": "TEXT"}


def identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError("Número não finito no SQLite")
        return str(value)
    if isinstance(value, str):
        if "\x00" in value:
            raise ValueError("Texto com byte NUL não pode ser importado no Postgres")
        return "'" + value.replace("'", "''") + "'"
    raise TypeError(f"Tipo não suportado no SQLite: {type(value).__name__}")


def table_info(connection: sqlite3.Connection, table: str) -> list[sqlite3.Row]:
    return connection.execute(f"PRAGMA table_info({identifier(table)})").fetchall()


def create_table(connection: sqlite3.Connection, table: str) -> tuple[str, bool]:
    original = connection.execute(
        "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)
    ).fetchone()[0]
    autoincrement = "AUTOINCREMENT" in original.upper()
    fields = []
    for column in table_info(connection, table):
        kind = TYPE_MAP.get(column["type"].upper())
        if kind is None:
            raise ValueError(f"Tipo não suportado: {table}.{column['name']} ({column['type']})")
        definition = f"  {identifier(column['name'])} {kind}"
        if autoincrement and column["pk"]:
            definition += " GENERATED BY DEFAULT AS IDENTITY"
        if column["pk"]:
            definition += " PRIMARY KEY"
        elif column["notnull"]:
            definition += " NOT NULL"
        if column["dflt_value"] is not None:
            definition += f" DEFAULT {column['dflt_value']}"
        fields.append(definition)

    for index in connection.execute(f"PRAGMA index_list({identifier(table)})"):
        if not index["unique"] or index["origin"] == "pk":
            continue
        if index["partial"]:
            raise ValueError(f"Índice parcial exige conversão manual: {table}.{index['name']}")
        columns = connection.execute(f"PRAGMA index_info({identifier(index['name'])})").fetchall()
        if any(column["name"] is None for column in columns):
            raise ValueError(f"Índice por expressão exige conversão manual: {table}.{index['name']}")
        fields.append("  UNIQUE (" + ", ".join(identifier(column["name"]) for column in columns) + ")")

    foreign_keys: dict[int, list[sqlite3.Row]] = {}
    for foreign_key in connection.execute(f"PRAGMA foreign_key_list({identifier(table)})"):
        foreign_keys.setdefault(foreign_key["id"], []).append(foreign_key)
    for group in foreign_keys.values():
        group.sort(key=lambda item: item["seq"])
        local = ", ".join(identifier(item["from"]) for item in group)
        remote = ", ".join(identifier(item["to"]) for item in group)
        fields.append(f"  FOREIGN KEY ({local}) REFERENCES public.{identifier(group[0]['table'])} ({remote})")

    name = f"public.{identifier(table)}"
    statements = [
        f"CREATE TABLE {name} (\n" + ",\n".join(fields) + "\n);",
        f"ALTER TABLE {name} ENABLE ROW LEVEL SECURITY;",
        f"REVOKE ALL ON TABLE {name} FROM anon, authenticated;",
    ]
    if autoincrement:
        statements.append(
            f"REVOKE ALL ON SEQUENCE public.{identifier(table + '_id_seq')} FROM anon, authenticated;"
        )
    return "\n".join(statements), autoincrement


def generate(connection: sqlite3.Connection, source_hash: str) -> tuple[str, str, str]:
    actual = {
        row["name"]
        for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'"
        )
    }
    if actual != set(TABLES):
        raise ValueError(f"Tabelas inesperadas ou ausentes: {sorted(actual ^ set(TABLES))}")
    if connection.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
        raise ValueError("SQLite falhou em integrity_check")
    if connection.execute("PRAGMA foreign_key_check").fetchall():
        raise ValueError("SQLite contém violações de chave estrangeira")

    header = (
        "-- Gerado de banco/gestao.db; SHA-256: " + source_hash + "\n"
        "-- Execute somente no projeto Supabase correto e vazio. Arquivo UTF-8.\n"
    )
    schema = [
        header,
        "-- 01: estrutura. Sem políticas de acesso; RLS e revogações bloqueiam anon/authenticated.",
        "-- TEXT e BIGINT preservam valores legados; REAL vira NUMERIC para valores decimais.",
        "BEGIN;",
    ]
    data = [
        header,
        "-- 02: DADOS PESSOAIS. Não versionar nem compartilhar publicamente.",
        "-- Executar uma única vez, depois de 01_schema.sql, no mesmo projeto.",
        "BEGIN;",
        "SET LOCAL standard_conforming_strings = on;",
    ]
    checks = [header, "-- 03: todas as contagens devem aparecer como OK."]
    counts = []
    sequences = []

    for table in TABLES:
        ddl, autoincrement = create_table(connection, table)
        schema.append(ddl)
        columns = [column["name"] for column in table_info(connection, table)]
        names = ", ".join(identifier(column) for column in columns)
        count = 0
        for row in connection.execute(f"SELECT {names} FROM {identifier(table)}"):
            values = ", ".join(literal(value) for value in row)
            data.append(f"INSERT INTO public.{identifier(table)} ({names}) VALUES ({values});")
            count += 1
        if autoincrement:
            sequence = connection.execute(
                "SELECT seq FROM sqlite_sequence WHERE name = ?", (table,)
            ).fetchone()
            previous = sequence[0] if sequence is not None else 0
            highest = connection.execute(
                f"SELECT MAX(\"id\") FROM {identifier(table)}"
            ).fetchone()[0] or 0
            expected_next = max(previous, highest) + 1
            sequence_name = f"public.{identifier(table + '_id_seq')}"
            sequences.append(
                f"('{table}', {expected_next}, (SELECT last_value + "
                f"CASE WHEN is_called THEN 1 ELSE 0 END FROM {sequence_name}))"
            )
            data.append(
                f"SELECT setval(pg_get_serial_sequence('public.{identifier(table)}', 'id'), "
                f"GREATEST(COALESCE(MAX(\"id\"), 0), {previous}, 1), "
                f"GREATEST(COALESCE(MAX(\"id\"), 0), {previous}) > 0) "
                f"FROM public.{identifier(table)};"
            )
        counts.append(f"('{table}', {count}, (SELECT COUNT(*) FROM public.{identifier(table)}))")

    schema.append("COMMIT;")
    data.append("COMMIT;")
    checks.extend(
        [
            "WITH contagens(tabela, esperado, encontrado) AS (",
            "  VALUES\n    " + ",\n    ".join(counts),
            ")",
            "SELECT tabela, esperado, encontrado,",
            "       CASE WHEN esperado = encontrado THEN 'OK' ELSE 'DIVERGENTE' END AS resultado",
            "FROM contagens ORDER BY tabela;",
        ]
    )
    checks.extend(
        [
            "\n-- Próximo ID de cada tabela com AUTOINCREMENT no SQLite.",
            "WITH sequencias(tabela, esperado, encontrado) AS (",
            "  VALUES\n    " + ",\n    ".join(sequences),
            ")",
            "SELECT tabela, esperado, encontrado,",
            "       CASE WHEN esperado = encontrado THEN 'OK' ELSE 'DIVERGENTE' END AS resultado",
            "FROM sequencias ORDER BY tabela;",
        ]
    )
    return ("\n\n".join(schema) + "\n", "\n".join(data) + "\n", "\n".join(checks) + "\n")


def structure_check(connection: sqlite3.Connection, source_hash: str) -> str:
    """Gera uma conferência independente de colunas, constraints e acesso."""
    expected = []
    for table in TABLES:
        columns = table_info(connection, table)
        original = connection.execute(
            "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", (table,)
        ).fetchone()[0]
        autoincrement = "AUTOINCREMENT" in original.upper()
        signature = "|".join(
            f"{column['name']}:{TYPE_MAP[column['type'].upper()].lower()}"
            f":{int(bool(column['notnull'] or column['pk']))}:{int(bool(autoincrement and column['pk']))}"
            for column in columns
        )
        defaults = sum(column["dflt_value"] is not None for column in columns)
        unique = sum(
            index["unique"] and index["origin"] != "pk"
            for index in connection.execute(f"PRAGMA index_list({identifier(table)})")
        )
        foreign = len({
            key["id"] for key in connection.execute(f"PRAGMA foreign_key_list({identifier(table)})")
        })
        expected.append(f"('{table}', {literal(signature)}, {defaults}, 1, {unique}, {foreign})")

    return (
        f"-- Gerado do esquema de banco/gestao.db; SHA-256 da origem: {source_hash}\n"
        "-- Execute após 01_schema.sql, antes de carregar os dados. Todas as linhas devem ser OK.\n"
        "WITH esperado(tabela, colunas, defaults, primarias, unicas, estrangeiras) AS (\n"
        "  VALUES\n    " + ",\n    ".join(expected) + "\n"
        "), conferido AS (\n"
        "  SELECT e.*, c.oid, c.relrowsecurity,\n"
        "    (SELECT string_agg(a.attname || ':' || format_type(a.atttypid, a.atttypmod) || ':' ||\n"
        "      CASE WHEN a.attnotnull THEN '1' ELSE '0' END || ':' ||\n"
        "      CASE WHEN a.attidentity = 'd' THEN '1' ELSE '0' END, '|' ORDER BY a.attnum)\n"
        "     FROM pg_attribute a WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped) AS colunas_encontradas,\n"
        "    (SELECT COUNT(*) FROM pg_attrdef d WHERE d.adrelid = c.oid) AS defaults_encontrados,\n"
        "    (SELECT COUNT(*) FROM pg_constraint x WHERE x.conrelid = c.oid AND x.contype = 'p') AS primarias_encontradas,\n"
        "    (SELECT COUNT(*) FROM pg_constraint x WHERE x.conrelid = c.oid AND x.contype = 'u') AS unicas_encontradas,\n"
        "    (SELECT COUNT(*) FROM pg_constraint x WHERE x.conrelid = c.oid AND x.contype = 'f') AS estrangeiras_encontradas,\n"
        "    COALESCE(has_table_privilege('anon', c.oid, 'SELECT') OR\n"
        "      has_table_privilege('anon', c.oid, 'INSERT') OR\n"
        "      has_table_privilege('anon', c.oid, 'UPDATE') OR\n"
        "      has_table_privilege('anon', c.oid, 'DELETE') OR\n"
        "      has_table_privilege('authenticated', c.oid, 'SELECT') OR\n"
        "      has_table_privilege('authenticated', c.oid, 'INSERT') OR\n"
        "      has_table_privilege('authenticated', c.oid, 'UPDATE') OR\n"
        "      has_table_privilege('authenticated', c.oid, 'DELETE'), TRUE) AS acesso_indevido\n"
        "  FROM esperado e LEFT JOIN pg_class c ON c.relname = e.tabela\n"
        "    AND c.relnamespace = 'public'::regnamespace AND c.relkind = 'r'\n"
        ")\n"
        "SELECT tabela, CASE\n"
        "  WHEN oid IS NULL THEN 'TABELA AUSENTE'\n"
        "  WHEN colunas IS DISTINCT FROM colunas_encontradas THEN 'COLUNAS/TIPOS DIFERENTES'\n"
        "  WHEN defaults <> defaults_encontrados THEN 'DEFAULTS DIFERENTES'\n"
        "  WHEN primarias <> primarias_encontradas OR unicas <> unicas_encontradas\n"
        "    OR estrangeiras <> estrangeiras_encontradas THEN 'CONSTRAINTS DIFERENTES'\n"
        "  WHEN NOT relrowsecurity THEN 'RLS DESLIGADO'\n"
        "  WHEN acesso_indevido THEN 'ACESSO INDEVIDO'\n"
        "  ELSE 'OK' END AS resultado\n"
        "FROM conferido ORDER BY tabela;\n"
    )


def main() -> None:
    source_hash = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    connection = sqlite3.connect(f"file:{SOURCE.resolve().as_posix()}?mode=ro", uri=True)
    connection.row_factory = sqlite3.Row
    try:
        schema, data, checks = generate(connection, source_hash)
        structure = structure_check(connection, source_hash)
    finally:
        connection.close()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for name, contents in (
        ("01_schema.sql", schema),
        ("02_dados.sql", data),
        ("03_verificacao.sql", checks),
        ("verificacao_estrutura.sql", structure),
    ):
        (OUTPUT / name).write_text(contents, encoding="utf-8")
    print(f"Scripts gerados em {OUTPUT} (02_dados.sql contém dados pessoais e fica fora do Git).")


if __name__ == "__main__":
    main()
